import type { TradingDashboardData } from './types';

const now = '2026-03-21T00:00:00.000Z';

export const demoTradingData: TradingDashboardData = {
  templates: [
    {
      id: 'tpl-profit-share-v1',
      name: 'Standard Profit Share',
      agreementType: 'profit_share',
      calculationMethod: 'profit_share',
      calculationConfig: { profitSharePercent: 12, percentages: { merchant: 12 }, currencyAssumptions: ['USD'] },
      defaultCurrency: 'USD',
      notes: 'Baseline merchant revenue share formula.',
      createdByUserId: 'demo-user',
      version: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'tpl-fixed-margin-v1',
      name: 'Fixed Margin Desk',
      agreementType: 'fixed_margin',
      calculationMethod: 'fixed_margin',
      calculationConfig: { fixedMarginAmount: 8, fixedValues: { marginPerUnit: 8 }, currencyAssumptions: ['USD'] },
      defaultCurrency: 'USD',
      notes: 'Fixed dollars per unit.',
      createdByUserId: 'demo-user',
      version: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  merchantAgreements: [
    {
      id: 'mag-northwind-v1',
      templateId: 'tpl-profit-share-v1',
      merchantId: 'merchant-northwind',
      merchantName: 'Northwind Payments',
      agreementType: 'profit_share',
      title: 'Northwind Profit Share 2026',
      status: 'approved',
      approvedByUserId: 'reviewer-1',
      approvedAt: now,
      resolvedTermsSnapshot: {
        agreementId: 'mag-northwind-v1',
        templateId: 'tpl-profit-share-v1',
        version: 1,
        agreementType: 'profit_share',
        profitSharePercent: 12,
        percentages: { merchant: 12 },
        currencyAssumptions: ['USD'],
      },
      version: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'mag-orbit-v1',
      templateId: 'tpl-fixed-margin-v1',
      merchantId: 'merchant-orbit',
      merchantName: 'Orbit Exchange',
      agreementType: 'fixed_margin',
      title: 'Orbit Fixed Margin 2026',
      status: 'pending',
      approvedByUserId: null,
      approvedAt: null,
      resolvedTermsSnapshot: {
        agreementId: 'mag-orbit-v1',
        templateId: 'tpl-fixed-margin-v1',
        version: 1,
        agreementType: 'fixed_margin',
        fixedMarginAmount: 8,
        fixedValues: { marginPerUnit: 8 },
        currencyAssumptions: ['USD'],
      },
      version: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  orders: [
    {
      id: 'ord-001',
      direction: 'incoming',
      merchantId: 'merchant-northwind',
      merchantName: 'Northwind Payments',
      buyerId: 'buyer-001',
      buyerName: 'Acme Treasury',
      merchantAgreementId: 'mag-northwind-v1',
      agreementTemplateId: 'tpl-profit-share-v1',
      agreementType: 'profit_share',
      agreementSnapshot: {
        agreementId: 'mag-northwind-v1',
        templateId: 'tpl-profit-share-v1',
        version: 1,
        agreementType: 'profit_share',
        profitSharePercent: 12,
        percentages: { merchant: 12 },
        currencyAssumptions: ['USD'],
      },
      quantity: 100,
      unitPrice: 250,
      totalAmount: 25000,
      currency: 'USD',
      computedNetProfit: 3000,
      status: 'confirmed',
      createdByUserId: 'demo-user',
      createdAt: now,
      updatedAt: now,
    },
  ],
};
